name = "silicon-key-pool"
main = "src/index.js"
compatibility_date = "2023-12-01"

# KV 命名空间配置
[[kv_namespaces]]
binding = "STATIC_CONTENT"
id = "your-kv-namespace-id"  # 替换为您的 KV 命名空间 ID

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "silicon_key_pool"
database_id = "your-d1-database-id"  # 替换为您的 D1 数据库 ID

# 环境变量 - 请在部署时替换这些值
[vars]
ADMIN_USERNAME = "admin"  # 更改为安全的用户名
ADMIN_PASSWORD = "password"  # 更改为安全的密码
API_KEY = ""  # 可选，用于保护 API 端点
BASE_URL = "https://api.siliconflow.cn"

# 自定义域名 - 如果需要
# [[routes]]
# pattern = "your-domain.com"
# custom_domain = true 